In [5]:
import sys
sys.path.append("../")

import pandas as pd
import os
import statsmodels.formula.api as sm

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

from library import regulations
from library import analysis
from library import tables

data_path = '/Users/kylieleblancKylie/domino/dofis/data/'

In [24]:
data = pd.read_csv(os.path.join(data_path, 'clean', 'master_data.csv'),
                  sep=",")
data = data[data.doi == True]
regs = data[regulations.mainless]
regs = regs.drop(['reg25_0811'], axis = 1)
regs.head()

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (8,9,10,280) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,reg25_081,reg25_0812,reg25_082,reg25_112,reg25_111,reg21_003,reg21_102,reg21_401,reg21_352,reg21_354,reg25_092,reg37_0012,reg25_036
3,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
4,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
5,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
7,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [25]:
frequent_itemsets = apriori(regs, min_support=0.07, use_colnames=True)
frequent_itemsets.head()

    support      itemsets
0  0.431124   (reg25_081)
1  0.247985  (reg25_0812)
2  0.268089   (reg25_082)
3  0.399251   (reg25_112)
4  0.132083   (reg25_111)

In [26]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules[['antecedents', 'consequents', 'confidence']].head(20)

     antecedents   consequents  confidence
0   (reg25_0812)   (reg25_081)    0.585621
1    (reg25_081)  (reg25_0812)    0.336852
2    (reg25_081)   (reg25_082)    0.492812
3    (reg25_082)   (reg25_081)    0.792508
4    (reg25_081)   (reg25_112)    0.469745
5    (reg25_112)   (reg25_081)    0.507246
6    (reg25_081)   (reg25_111)    0.172975
7    (reg25_111)   (reg25_081)    0.564598
8    (reg21_003)   (reg25_081)    0.466375
9    (reg25_081)   (reg21_003)    0.863558
10   (reg21_102)   (reg25_081)    0.460511
11   (reg25_081)   (reg21_102)    0.346724
12   (reg25_081)   (reg21_401)    0.177389
13   (reg21_401)   (reg25_081)    0.540103
14   (reg25_081)   (reg21_352)    0.218835
15   (reg21_352)   (reg25_081)    0.468674
16   (reg25_092)   (reg25_081)    0.605999
17   (reg25_081)   (reg25_092)    0.516561
18  (reg37_0012)   (reg25_081)    0.581008
19   (reg25_081)  (reg37_0012)    0.366606

In [29]:
rules.antecendents

AttributeError: 'DataFrame' object has no attribute 'antecendents'