In [1]:
import sys
sys.path.append("../")

import pandas as pd
import os
import statsmodels.formula.api as sm

from library import regulations
from library import analysis
from library import tables

In [2]:
data_path = '/Users/kylieleblancKylie/domino/dofis/data/'
table_path = '/Users/kylieleblancKylie/domino/dofis/results/descriptive/'
data = pd.read_csv(os.path.join(data_path, 'clean', 'master_data.csv'),
                  sep=",")

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data = data[data.year == 'yr1415']
data

,Unnamed: 0,district,distname,year,cntyname,distischarter,rating_academic,rating_financial,eligible,type,...,charter,district_status,type_urban,type_suburban,type_town,type_rural,teachers_nodegree,teachers_badegree,teachers_msdegree,teachers_phddegree
3619,3619,1902,CAYUGA ISD,yr1415,ANDERSON,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.460037,0.041822,0.000000
3620,3620,1903,ELKHART ISD,yr1415,ANDERSON,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.000000,0.510386,0.087240,0.000000
3621,3621,1904,FRANKSTON ISD,yr1415,ANDERSON,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000865,0.455882,0.035467,0.000000
3622,3622,1906,NECHES ISD,yr1415,ANDERSON,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.558292,0.011494,0.000000
3623,3623,1907,PALESTINE ISD,yr1415,ANDERSON,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.016495,0.467010,0.069072,0.000000
3624,3624,1908,WESTWOOD ISD,yr1415,ANDERSON,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.000000,0.502875,0.064131,0.004423
3625,3625,1909,SLOCUM ISD,yr1415,ANDERSON,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.011765,0.605042,0.016807,0.000000
3626,3626,2901,ANDREWS ISD,yr1415,ANDREWS,N,M,Pass,True,D,...,False,tps,0,1,0,0,0.000000,0.421481,0.110582,0.001985
3627,3627,3801,PINEYWOODS COMMUNITY ACADEMY,yr1415,ANGELINA,Y,M,Pass,False,I,...,True,charter,0,0,1,0,0.020704,0.351967,0.144928,0.000000
3628,3628,3902,HUDSON ISD,yr1415,ANGELINA,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.012782,0.385464,0.087469,0.000000
3629,3629,3903,LUFKIN ISD,yr1415,ANGELINA,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.006290,0.403952,0.065565,0.000000
3630,3630,3904,HUNTINGTON ISD,yr1415,ANGELINA,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.000000,0.414644,0.073220,0.000405
3631,3631,3905,DIBOLL ISD,yr1415,ANGELINA,N,M,Pass,True,G,...,False,tps,0,0,1,0,0.000000,0.423635,0.087077,0.000000
3632,3632,3906,ZAVALLA ISD,yr1415,ANGELINA,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.475842,0.067350,0.000000
3633,3633,3907,CENTRAL ISD,yr1415,ANGELINA,N,M,Pass,True,G,...,False,tps,0,0,1,0,0.000000,0.446239,0.067998,0.000000
3634,3634,4901,ARANSAS COUNTY ISD,yr1415,ARANSAS,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.004085,0.372753,0.103758,0.006127
3635,3635,5901,ARCHER CITY ISD,yr1415,ARCHER,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.526316,0.033595,0.000000
3636,3636,5902,HOLLIDAY ISD,yr1415,ARCHER,N,M,Pass,True,D,...,False,doi,0,1,0,0,0.000000,0.481013,0.092827,0.000000
3637,3637,5904,WINDTHORST ISD,yr1415,ARCHER,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.448120,0.090226,0.000000
3638,3638,6902,CLAUDE ISD,yr1415,ARMSTRONG,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.473451,0.085546,0.000000
3639,3639,7901,CHARLOTTE ISD,yr1415,ATASCOSA,N,M,Pass,True,H,...,False,tps,0,0,0,1,0.000000,0.397849,0.086022,0.000000
3640,3640,7902,JOURDANTON ISD,yr1415,ATASCOSA,N,M,Pass,True,F,...,False,doi,0,0,1,0,0.000000,0.408940,0.137423,0.000000
3641,3641,7904,LYTLE ISD,yr1415,ATASCOSA,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.000000,0.348456,0.114373,0.000000
3642,3642,7905,PLEASANTON ISD,yr1415,ATASCOSA,N,M,Pass,True,E,...,False,tps,0,0,1,0,0.000000,0.432159,0.065614,0.000000
3643,3643,7906,POTEET ISD,yr1415,ATASCOSA,N,M,Pass,True,G,...,False,tps,0,0,1,0,0.003504,0.322004,0.100561,0.000000
3644,3644,8901,BELLVILLE ISD,yr1415,AUSTIN,N,M,Pass,True,E,...,False,tps,0,0,1,0,0.006483,0.445381,0.048298,0.004862
3645,3645,8902,SEALY ISD,yr1415,AUSTIN,N,M,Pass,True,D,...,False,tps,0,1,0,0,0.002860,0.484415,0.080355,0.000000
3646,3646,8903,BRAZOS ISD,yr1415,AUSTIN,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.430782,0.087948,0.000000
3647,3647,9901,MULESHOE ISD,yr1415,BAILEY,N,M,Fail,False,G,...,False,doi,0,0,1,0,0.000000,0.418165,0.084532,0.002248
3648,3648,10901,MEDINA ISD,yr1415,BANDERA,N,M,Pass,True,H,...,False,tps,0,0,0,1,0.000000,0.404594,0.106007,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4808,4808,246912,THRALL ISD,yr1415,WILLIAMSON,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.470035,0.104583,0.000000
4809,4809,246913,LEANDER ISD,yr1415,WILLIAMSON,N,M,Pass,True,B,...,False,doi,0,1,0,0,0.001381,0.394433,0.144439,0.003660
4810,4810,246914,COUPLAND ISD,yr1415,WILLIAMSON,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.046729,0.523364,0.000000,0.000000
4811,4811,247901,FLORESVILLE ISD,yr1415,WILSON,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.003365,0.319650,0.097241,0.001682
4812,4812,247903,LA VERNIA ISD,yr1415,WILSON,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.000000,0.369458,0.099015,0.000000
4813,4813,247904,POTH ISD,yr1415,WILSON,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.471803,0.064337,0.000000
4814,4814,247906,STOCKDALE ISD,yr1415,WILSON,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.454161,0.064175,0.000000
4815,4815,248901,KERMIT ISD,yr1415,WINKLER,N,M,Pass,True,D,...,False,tps,0,1,0,0,0.000000,0.362357,0.067722,0.000000
4816,4816,248902,WINK-LOVING ISD,yr1415,WINKLER,N,M,Pass,True,F,...,False,doi,0,0,1,0,0.000000,0.469220,0.068399,0.000000
4817,4817,249901,ALVORD ISD,yr1415,WISE,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.431193,0.097248,0.000000
4818,4818,249902,BOYD ISD,yr1415,WISE,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.000000,0.443030,0.093333,0.000000
4819,4819,249903,BRIDGEPORT ISD,yr1415,WISE,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.003328,0.411647,0.109484,0.006656
4820,4820,249904,CHICO ISD,yr1415,WISE,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.527215,0.053362,0.000000
4821,4821,249905,DECATUR ISD,yr1415,WISE,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.002385,0.386835,0.104937,0.000000
4822,4822,249906,PARADISE ISD,yr1415,WISE,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.000000,0.502366,0.085869,0.000000
4823,4823,249908,SLIDELL ISD,yr1415,WISE,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.390411,0.159817,0.000000
4824,4824,250902,HAWKINS ISD,yr1415,WOOD,N,M,Pass,True,H,...,False,tps,0,0,0,1,0.000000,0.438474,0.063084,0.000000
4825,4825,250903,MINEOLA ISD,yr1415,WOOD,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.000000,0.433018,0.168245,0.000000
4826,4826,250904,QUITMAN ISD,yr1415,WOOD,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.023753,0.397862,0.121140,0.000000
4827,4827,250905,YANTIS ISD,yr1415,WOOD,N,M,Pass,True,H,...,False,tps,0,0,0,1,0.000000,0.527157,0.079872,0.000000
4828,4828,250906,ALBA-GOLDEN ISD,yr1415,WOOD,N,M,Pass,True,H,...,False,tps,0,0,0,1,0.007981,0.510774,0.059058,0.000000
4829,4829,250907,WINNSBORO ISD,yr1415,WOOD,N,M,Pass,True,E,...,False,doi,0,0,1,0,0.000000,0.431391,0.076071,0.000000
4830,4830,251901,DENVER CITY ISD,yr1415,YOAKUM,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.000000,0.467350,0.048229,0.000000
4831,4831,251902,PLAINS ISD,yr1415,YOAKUM,N,M,Pass,True,H,...,False,tps,0,0,0,1,0.012048,0.487952,0.062651,0.000000
4832,4832,252901,GRAHAM ISD,yr1415,YOUNG,N,M,Pass,True,G,...,False,doi,0,0,1,0,0.000284,0.442395,0.072361,0.000000
4833,4833,252902,NEWCASTLE ISD,yr1415,YOUNG,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.394366,0.169014,0.000000
4834,4834,252903,OLNEY ISD,yr1415,YOUNG,N,M,Pass,True,H,...,False,doi,0,0,0,1,0.000000,0.474106,0.053975,0.000729
4835,4835,253901,ZAPATA COUNTY ISD,yr1415,ZAPATA,N,M,Pass,True,D,...,False,doi,0,1,0,0,0.003770,0.374364,0.061828,0.000000
4836,4836,254901,CRYSTAL CITY ISD,yr1415,ZAVALA,N,I,Pass,False,G,...,False,tps,0,0,1,0,0.003004,0.349054,0.038750,0.000000
4837,4837,254902,LA PRYOR ISD,yr1415,ZAVALA,N,M,Pass,True,H,...,False,tps,0,0,0,1,0.000000,0.372738,0.132690,0.000000

## Schedules

In [4]:
df = analysis.many_x_one_y(data = data, x_list = regulations.schedules,
                         x_labels = regulations.labels, y = 'students_black')
tables.var_diff_to_excel(file = table_path + 'reg_blackXexemption.xlsx', 
                         df = df, 
                         control_col = 'Control', 
                         diff_col = 'Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 5)
df

,Characteristic,Control,Difference,Std. Error,P-value
0,25.0811 - Minimum First Day of Instruction,0.06,0.01,0.01,0.64
1,25.081 - Minimum Minutes of Operation,0.07,-0.01,0.01,0.38
2,25.0812 - Minimum Last Day of Instruction,0.07,-0.01,0.01,0.54
3,25.082 - Pledge of Allegiance and Minute of Si...,0.07,-0.01,0.01,0.36

## Class Size

In [5]:
df = analysis.many_x_one_y(data = data, x_list = regulations.class_size,
                         x_labels = regulations.labels, y = 'students_black')
tables.var_diff_to_excel(file = table_path + 'reg_blackXexemption.xlsx', 
                         df = df, 
                         control_col = 'Control', 
                         diff_col = 'Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 5)
df

,Characteristic,Control,Difference,Std. Error,P-value
0,25.112 - Class Size Maximum,0.07,0.01,0.01,0.35
1,25.113 - Notice of Class Size,0.07,0.00,0.01,0.65
2,25.111 - Maximum Student Teacher Ratio,0.07,0.00,0.01,0.69

## Certification

In [6]:
df = analysis.many_x_one_y(data = data, x_list = regulations.certification,
                         x_labels = regulations.labels, y = 'students_black')
tables.var_diff_to_excel(file = table_path + 'reg_blackXexemption.xlsx', 
                         df = df, 
                         control_col = 'Control', 
                         diff_col = 'Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 5)
df

,Characteristic,Control,Difference,Std. Error,P-value
0,21.003 - Teacher Certification Required,0.06,0.01,0.01,0.25
1,21.053 - Presentation of Teacher Certificates,0.07,-0.00,0.01,0.80
2,21.057 - Notice of Uncertified Teacher,0.07,-0.01,0.01,0.23

## Contracts

In [7]:
df = analysis.many_x_one_y(data = data, x_list = regulations.contracts,
                         x_labels = regulations.labels, y = 'students_black')
tables.var_diff_to_excel(file = table_path + 'reg_blackXexemption.xlsx', 
                         df = df, 
                         control_col = 'Control', 
                         diff_col = 'Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 5)
df

,Characteristic,Control,Difference,Std. Error,P-value
0,21.102 - Maximum Probationary Contract Length,0.07,-0.01,0.01,0.41
1,21.401 - Minimum Service Days Required for Tea...,0.08,-0.02,0.01,0.01
2,21.352 - Teacher Evaluation,0.07,-0.00,0.01,0.94
3,21.354 - Administrator Evaluation,0.07,-0.03,0.01,0.06

## Student Behavior

In [8]:
df = analysis.many_x_one_y(data = data, x_list = regulations.behavior,
                         x_labels = regulations.labels, y = 'students_black')
tables.var_diff_to_excel(file = table_path + 'reg_blackXexemption.xlsx', 
                         df = df, 
                         control_col = 'Control', 
                         diff_col = 'Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 5)
df

,Characteristic,Control,Difference,Std. Error,P-value
0,25.092 - Minimum Attendance for Class Credit,0.06,0.02,0.01,0.00
1,37.0012 - Designation of Campus Behavior Coord...,0.06,0.02,0.01,0.01
2,25.036 - Transfers,0.07,-0.01,0.01,0.50