In [3]:
import pandas as pd
import os
import statsmodels.formula.api as sm
import numpy as np

from library import regulations
from library import characteristics
from library import analysis
from library import tables

In [4]:
data_path = '/Users/kylieleblancKylie/domino/dofis/data/'
table_path = '/Users/kylieleblancKylie/domino/dofis/results/descriptive/'
data = pd.read_csv(os.path.join(data_path, 'clean', 'master_data.csv'),
                  sep=",")

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Just keep eligible districts from 2014-15

In [5]:
data = data[data.year == 'yr1415']
data = data[data.eligible == 1]

Generate opt out variable

In [6]:
data['optout'] = np.where((data['district_status'] != 'doi'), True, False)
data.head()

,Unnamed: 0,district,distname,year,cntyname,distischarter,rating_academic,rating_financial,eligible,type,...,alg_std,bio_std,eng1_std,eng2_std,us_std,math,reading,avescores,students_teacher_ratio,optout
3682,3682,1902,CAYUGA ISD,yr1415,ANDERSON,N,M,Pass,1.0,H,...,0.661039,0.688869,0.593574,0.737335,0.109439,0.714925,0.756997,0.683635,5.362454,False
3683,3683,1903,ELKHART ISD,yr1415,ANDERSON,N,M,Pass,1.0,G,...,0.295768,-0.013381,0.677605,1.086656,1.255590,0.253594,0.526180,0.469464,7.222552,False
3684,3684,1904,FRANKSTON ISD,yr1415,ANDERSON,N,M,Pass,1.0,H,...,0.702653,0.719402,0.643004,-0.072455,-0.093420,0.315321,0.626085,0.443978,6.946367,False
3685,3685,1906,NECHES ISD,yr1415,ANDERSON,N,M,Pass,1.0,H,...,-0.222086,0.999284,-0.642171,-1.104541,-0.093420,0.074073,0.619741,0.182350,6.075534,False
3686,3686,1907,PALESTINE ISD,yr1415,ANDERSON,N,M,Pass,1.0,E,...,0.235660,0.327567,-0.716316,-0.702292,-0.478851,0.094497,-0.738283,-0.305703,6.911340,False

Some basic descriptives

In [7]:
num_dois = len(data[data.doi == 1])
num_tps = len(data[data.doi == 0])
print(str(len(data)) + ' eligible districts, ' + str(num_dois), 'are DOIs and ' + str(num_tps) + ' have opted  out.')

973 eligible districts, 762 are DOIs and 211 have opted  out.

## District Characteristics

In [8]:
# Traditional public schools versus DOI
district = analysis.many_y_one_x(data = data, 
                                 y_list = characteristics.geography,
                                 y_labels = characteristics.labels,
                                 x = 'optout')
district
# note, I don't have the geographic characteristics of charter schools

  Characteristic  Control  Difference  Std. Error  P-value
0          Urban     0.05        0.01        0.02     0.50
1       Suburban     0.25        0.00        0.03     0.98
2           Town     0.29       -0.05        0.03     0.16
3          Rural     0.42        0.04        0.04     0.35

## Teacher Characteristics

In [9]:
teacher = analysis.many_y_one_x(data = data, 
                                 y_list = characteristics.teacher,
                                 y_labels = characteristics.labels,
                                 x = 'optout')
teacher

                Characteristic  Control  Difference  Std. Error  P-value
0  Ave. Experience in District    12.53       -0.40        0.19     0.03
1     Ave. Experience Teaching     7.38       -0.07        0.15     0.63
2       Teacher Turnover Ratio    18.83        1.16        0.68     0.09
3        Student-Teacher Ratio     6.70       -0.30        0.09     0.00

## Student Characteristics

In [10]:
student = analysis.many_y_one_x(data = data, 
                                 y_list = characteristics.student,
                                 y_labels = characteristics.labels,
                                 x = 'optout')
student

                     Characteristic  Control  Difference  Std. Error  P-value
0                  Percent Hispanic     0.35        0.16        0.02     0.00
1                     Percent White     0.55       -0.13        0.02     0.00
2                     Percent Black     0.07       -0.02        0.01     0.04
3       Percent Econ. Disadvantaged     0.54        0.08        0.01     0.00
4  Average STAAR Performance (Std.)     0.16       -0.29        0.05     0.00

## To table

In [11]:
dfs = [district, teacher, student]
rows = [6, 15, 24]
tables.n_to_excel(file = table_path + 'TPS v. DOI v. Charter.xlsx',
                 col = 2, row = 4, n = len(data[data.doi == 0]))
tables.n_to_excel(file = table_path + 'TPS v. DOI v. Charter.xlsx',
                 col = 3, row = 4, n = len(data[data.doi == 1]))
for df, row in zip(dfs,rows):
    tables.var_diff_to_excel(file = table_path + 'TPS v. DOI v. Charter.xlsx', 
                             df = df, 
                             control_col = 'Control', 
                             diff_col = 'Difference', 
                             se_col = 'Std. Error', pvalue_col = 'P-value',
                             start_col = 2, start_row = row)

# Add charter columns

In [12]:
data = pd.read_csv(os.path.join(data_path, 'clean', 'master_data.csv'),
                  sep=",")
data[(data['eligible'] == True) | (data['charter'] == True)]
data[(data['district_status'] == 'tps') | (data['charter'] == True)]

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,district,distname,year,cntyname,distischarter,rating_academic,rating_financial,eligible,type,...,m_8th_std,alg_std,bio_std,eng1_std,eng2_std,us_std,math,reading,avescores,students_teacher_ratio
7,7,2901,ANDREWS ISD,yr1112,ANDREWS,N,NaN,NaN,NaN,D,...,0.978847,-0.670585,-1.458591,-0.844834,NaN,NaN,0.049887,-0.434597,-0.352151,7.585639
8,8,3801,PINEYWOODS COMMUNITY ACADEMY,yr1112,ANGELINA,Y,NaN,NaN,NaN,I,...,-0.713670,-0.111118,-1.082022,-0.306049,NaN,-2.187935,-0.492347,-0.685146,-0.672005,7.777622
12,12,3905,DIBOLL ISD,yr1112,ANGELINA,N,NaN,NaN,NaN,G,...,0.142097,-0.226710,-1.646875,-1.294645,NaN,NaN,0.159871,-0.409356,-0.311009,7.160818
14,14,3907,CENTRAL ISD,yr1112,ANGELINA,N,NaN,NaN,NaN,G,...,1.302136,0.342005,-0.898826,-0.246733,NaN,NaN,0.711367,0.052606,0.252019,7.301466
20,20,7901,CHARLOTTE ISD,yr1112,ATASCOSA,N,NaN,NaN,NaN,H,...,-1.189095,-1.771024,-2.196462,-2.036093,NaN,-2.309650,-1.584866,-1.776806,-1.780203,6.483667
23,23,7905,PLEASANTON ISD,yr1112,ATASCOSA,N,NaN,NaN,NaN,E,...,0.522438,-1.109836,-1.621431,-1.151299,NaN,NaN,0.533409,-0.173119,-0.114722,6.604064
24,24,7906,POTEET ISD,yr1112,ATASCOSA,N,NaN,NaN,NaN,G,...,-0.295295,-1.045104,-1.804627,-1.759286,NaN,NaN,-0.362876,-0.613177,-0.697689,7.012595
25,25,8901,BELLVILLE ISD,yr1112,AUSTIN,N,NaN,NaN,NaN,E,...,0.674574,0.517705,0.037507,0.638061,NaN,-1.183785,0.619735,0.424312,0.392111,6.827553
26,26,8902,SEALY ISD,yr1112,AUSTIN,N,NaN,NaN,NaN,D,...,1.073932,0.087701,-0.919181,-0.508711,NaN,NaN,0.481484,-0.146172,0.044779,8.213319
29,29,10901,MEDINA ISD,yr1112,BANDERA,N,NaN,NaN,NaN,H,...,-0.466448,-0.911017,-0.618944,0.494715,0.245110,NaN,-0.084010,0.862496,0.242549,4.167873
30,30,10902,BANDERA ISD,yr1112,BANDERA,N,NaN,NaN,NaN,B,...,0.712608,0.124691,-0.186399,-0.261562,NaN,NaN,0.043320,0.229737,0.087672,7.067599
34,34,11905,MCDADE ISD,yr1112,BASTROP,N,NaN,NaN,NaN,H,...,1.435256,0.152433,NaN,NaN,NaN,NaN,-0.685140,-0.594688,-0.578964,5.717689
36,36,13801,ST MARY'S ACADEMY CHARTER SCHOOL,yr1112,BEE,Y,NaN,NaN,NaN,I,...,NaN,NaN,NaN,NaN,NaN,NaN,0.118185,0.309464,0.213825,6.049496
41,41,14801,RICHARD MILBURN ALTER HIGH SCHOOL,yr1112,BELL,Y,NaN,NaN,NaN,I,...,NaN,-2.367481,-2.654451,-2.812141,-2.237189,NaN,NaN,NaN,-2.517815,8.709853
42,42,14802,TRANSFORMATIVE CHARTER ACADEMY,yr1112,BELL,Y,NaN,NaN,NaN,I,...,NaN,-1.937477,-1.819893,-0.839891,-1.332129,-2.076363,NaN,NaN,-1.601150,5.444444
43,43,14803,TEMPLE EDUCATION CENTER,yr1112,BELL,Y,NaN,NaN,NaN,I,...,-0.580550,-1.609195,-2.298237,-1.566509,-1.612644,-2.953726,-1.488368,-0.770684,-1.387919,12.892323
44,44,14804,ORENDA CHARTER SCHOOL,yr1112,BELL,Y,NaN,NaN,NaN,I,...,-1.835675,-1.253170,-1.489123,-0.696544,1.001972,-1.863361,-0.364498,-0.001275,-0.382051,10.453095
46,46,14902,BARTLETT ISD,yr1112,BELL,N,NaN,NaN,NaN,H,...,-0.998925,-1.918982,-2.120131,-1.620882,NaN,NaN,-1.134451,-0.885167,-1.185180,6.597628
48,48,14905,HOLLAND ISD,yr1112,BELL,N,NaN,NaN,NaN,H,...,0.579489,0.110820,-1.168531,-0.399965,NaN,NaN,0.718057,0.296286,0.308559,6.400335
49,49,14906,KILLEEN ISD,yr1112,BELL,N,NaN,NaN,NaN,C,...,-0.295295,-0.296065,-0.618944,-0.236847,NaN,-2.071291,-0.148932,-0.135206,-0.307998,6.915554
51,51,14908,SALADO ISD,yr1112,BELL,N,NaN,NaN,NaN,D,...,0.351285,0.323510,0.383543,0.672662,NaN,NaN,0.829760,1.229671,0.915754,7.825793
52,52,14909,TEMPLE ISD,yr1112,BELL,N,NaN,NaN,NaN,D,...,-0.314312,-0.434776,-1.326283,-0.745974,-2.216018,NaN,-0.502369,-0.711010,-0.750208,7.175153
53,53,14910,TROY ISD,yr1112,BELL,N,NaN,NaN,NaN,G,...,0.389319,0.397489,-0.705453,-0.147873,NaN,-1.924219,-0.324848,-0.031192,-0.282269,7.714861
54,54,15801,POR VIDA ACADEMY,yr1112,BEXAR,Y,NaN,NaN,NaN,I,...,NaN,-2.589418,-2.481433,-2.149781,NaN,-3.734732,NaN,NaN,-2.738841,5.082062
55,55,15802,GEORGE GERVIN ACADEMY,yr1112,BEXAR,Y,NaN,NaN,NaN,I,...,-0.561533,-2.307372,-2.781670,-2.327729,NaN,NaN,-1.094329,-1.150142,-1.392240,17.728791
56,56,15803,HIGGS CARTER KING GIFTED & TALENTE,yr1112,BEXAR,Y,NaN,NaN,NaN,I,...,-0.086107,-0.864780,-0.990424,-0.820119,NaN,NaN,-1.009406,-0.840966,-0.918504,13.611111
57,57,15805,NEW FRONTIERS CHARTER SCHOOL,yr1112,BEXAR,Y,NaN,NaN,NaN,I,...,-0.599567,NaN,NaN,NaN,NaN,NaN,-1.265122,-1.145184,-1.205153,8.498742
58,58,15806,SCHOOL OF EXCELLENCE IN EDUCATION,yr1112,BEXAR,Y,NaN,NaN,NaN,I,...,-0.409397,0.406736,-1.010779,-1.012895,-0.924587,NaN,-0.257295,-0.410944,-0.409435,5.580633
59,59,15807,SOUTHWEST PREPARATORY SCHOOL,yr1112,BEXAR,Y,NaN,NaN,NaN,I,...,NaN,-1.997585,-2.445812,-1.517079,NaN,NaN,NaN,NaN,-1.986825,4.893862
60,60,15808,JOHN H WOOD JR PUBLIC CHARTER DIST,yr1112,BEXAR,Y,NaN,NaN,NaN,I,...,-2.330118,-2.802108,-3.163328,-3.064233,NaN,NaN,-3.181164,-3.512119,-3.268930,4.288531
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8402,8402,227910,DEL VALLE ISD,yr1718,TRAVIS,N,M,Pass,1.0,B,...,0.294233,-0.134236,-0.303441,-1.171071,-1.067492,0.357940,-0.310707,-1.147620,-0.651074,6.845760
8406,8406,228903,TRINITY ISD,yr1718,TRINITY,N,I,Pass,0.0,G,...,0.066029,-0.605853,-0.822495,-1.255101,-0.998686,-0.275993,-0.737892,-1.441473,-1.002019,7.456716
8415,8415,230902,GILMER ISD,yr1718,UPSHUR,N,M,Pass,1.0,D,...,2.462176,1.386959,0.098572,-0.395022,0.329794,0.996945,0.654677,-0.456396,0.212173,6.610959
8426,8426,232904,UTOPIA ISD,yr1718,UVALDE,N,M,Pass,1.0,H,...,NaN,0.457597,-0.506991,-0.434566,0.546796,-0.103563,0.188142,0.335818,0.182181,5.860215
8429,8429,234801,RANCH ACADEMY,yr1718,VAN ZANDT,Y,X,Pass,0.0,I,...,NaN,-2.122425,-1.061667,-1.981720,-1.210396,0.256511,NaN,NaN,-1.223939,9.193548
8432,8432,234904,GRAND SALINE ISD,yr1718,VAN ZANDT,N,M,Pass,1.0,G,...,-0.523499,-0.069504,0.052773,-0.078671,-0.167725,0.895516,0.014368,-0.369782,-0.088241,5.877863
8437,8437,235901,BLOOMINGTON ISD,yr1718,VICTORIA,N,M,Pass,1.0,G,...,-0.371363,-1.012738,-0.506991,-1.566509,-0.966929,-0.108634,-0.725860,-1.642428,-1.080678,6.585185
8440,8440,236801,RAVEN SCHOOL,yr1718,WALKER,Y,X,Pass,0.0,I,...,NaN,-2.594042,-4.094572,-4.359295,-3.671523,-1.341000,NaN,NaN,-3.212086,3.955556
8443,8443,237902,HEMPSTEAD ISD,yr1718,WALLER,N,I,Pass,0.0,G,...,-0.504482,-0.823167,-1.728295,-1.279816,-0.628194,0.165225,-1.006720,-1.895851,-1.277040,6.817610
8444,8444,237904,WALLER ISD,yr1718,WALLER,N,M,Pass,1.0,E,...,0.807694,1.044806,0.928041,-0.137987,-0.162432,1.022302,0.831392,0.203391,0.523731,8.024170
8445,8445,237905,ROYAL ISD,yr1718,WALLER,N,M,Pass,1.0,D,...,0.275216,-0.397787,-0.333973,-1.526965,-1.416813,-0.012277,-0.550014,-1.453718,-0.924130,7.448015
8447,8447,238904,GRANDFALLS-ROYALTY ISD,yr1718,WARD,N,M,Pass,1.0,H,...,0.408336,0.166304,-2.008178,-0.627342,-0.035406,0.469513,-0.443203,-1.344136,-0.750538,5.500000
8450,8450,240801,GATEWAY ACADEMY CHARTER DISTRICT,yr1718,WEBB,Y,A,Pass,0.0,I,...,NaN,-1.345644,-2.654451,-2.886286,-2.655316,-1.589502,NaN,NaN,-2.226240,6.372549
8453,8453,240904,WEBB ISD,yr1718,WEBB,N,M,Pass,1.0,H,...,-1.036959,0.822869,0.307211,0.356311,0.922581,0.286940,-0.238103,-0.430444,-0.077375,4.048913
8454,8454,241901,BOLING ISD,yr1718,WHARTON,N,M,Pass,1.0,D,...,0.617523,0.494586,0.485318,0.346425,0.599724,-0.093420,0.741339,-0.181341,0.305449,7.951977
8458,8458,241906,LOUISE ISD,yr1718,WHARTON,N,M,Pass,1.0,H,...,0.731625,-0.314560,0.261413,-0.207189,-0.120090,0.530370,0.532258,0.160510,0.253326,6.981132
8464,8464,243902,ELECTRA ISD,yr1718,WICHITA,N,M,Pass,1.0,H,...,0.712608,1.165022,0.470052,0.608403,1.647687,1.879380,0.207627,-0.223509,0.333839,5.525292
8471,8471,245901,LASARA ISD,yr1718,WILLACY,N,M,Pass,1.0,H,...,-1.607470,0.522329,0.225791,-0.207189,0.530918,0.931016,-0.253905,0.119075,0.070229,5.409035
8472,8472,245902,LYFORD ISD,yr1718,WILLACY,N,M,Pass,1.0,G,...,0.237182,0.439102,-1.158354,-1.586281,-0.829318,-0.666495,0.367591,0.158792,-0.037826,5.747253
8473,8473,245903,RAYMONDVILLE ISD,yr1718,WILLACY,N,M,Pass,1.0,D,...,-0.333329,0.124691,-0.822495,-1.299588,-0.871660,0.363012,0.106371,-0.292742,-0.213192,6.180348
8474,8474,245904,SAN PERLITA ISD,yr1718,WILLACY,N,M,Pass,1.0,H,...,0.750642,0.489963,-0.975158,-1.843316,-0.390020,0.738300,1.483084,0.265203,0.500558,5.083488
8475,8475,246801,MERIDIAN WORLD SCHOOL LLC,yr1718,WILLIAMSON,Y,M,Pass,0.0,I,...,0.788676,1.585778,2.159523,2.289018,2.298695,3.253747,0.925745,2.106882,1.751913,9.902439
8478,8478,246905,GRANGER ISD,yr1718,WILLIAMSON,N,M,Pass,1.0,H,...,1.511324,1.017064,-0.196576,0.682548,0.605016,0.819444,0.314238,-0.102835,0.246818,6.485671
8491,8491,248901,KERMIT ISD,yr1718,WINKLER,N,M,Pass,1.0,D,...,-0.561533,-1.280912,-1.601076,-1.403391,-1.596766,-0.681710,-0.796866,-1.394599,-1.159567,7.002494
8500,8500,250902,HAWKINS ISD,yr1718,WOOD,N,M,Pass,1.0,H,...,0.769659,0.198670,0.668514,0.292052,0.043985,-0.301350,0.745325,0.236002,0.399402,5.614722
8503,8503,250905,YANTIS ISD,yr1718,WOOD,N,M,Pass,1.0,H,...,-0.257261,-0.388539,0.597271,-0.479053,-0.342385,1.504091,0.404889,-0.116742,0.154133,6.321070
8504,8504,250906,ALBA-GOLDEN ISD,yr1718,WOOD,N,M,Pass,1.0,G,...,1.092949,-0.078752,-0.812317,0.222851,0.605016,-0.174563,0.388209,0.432519,0.275682,7.079646
8507,8507,251902,PLAINS ISD,yr1718,YOAKUM,N,M,Pass,1.0,H,...,0.066029,0.281896,1.202835,1.033500,2.044643,0.368083,-0.795529,-1.299634,-0.449413,6.002621
8512,8512,254901,CRYSTAL CITY ISD,yr1718,ZAVALA,N,M,Pass,1.0,G,...,-0.295295,0.240283,-0.171133,-0.968408,-0.453533,-0.083277,-0.565180,-1.197822,-0.706711,4.979253
8513,8513,254902,LA PRYOR ISD,yr1718,ZAVALA,N,M,Pass,1.0,H,...,-0.675635,0.355876,-1.143087,-0.706430,0.133962,-0.286136,0.415188,0.002250,0.050518,5.904059

In [14]:
teacher = analysis.many_y_one_x(data = data, 
                                 y_list = characteristics.teacher,
                                 y_labels = characteristics.labels,
                                 x = 'charter')
teacher

                Characteristic  Control  Difference  Std. Error  P-value
0  Ave. Experience in District    12.50       -7.02        0.08     0.00
1     Ave. Experience Teaching     7.39       -5.13        0.06     0.00
2       Teacher Turnover Ratio    18.40       16.46        0.32     0.00
3        Student-Teacher Ratio     6.60       37.90       13.91     0.01

In [16]:
student = analysis.many_y_one_x(data = data, 
                                 y_list = characteristics.student,
                                 y_labels = characteristics.labels,
                                 x = 'charter')
student

                     Characteristic  Control  Difference  Std. Error  P-value
0                  Percent Hispanic     0.39        0.11        0.01      0.0
1                     Percent White     0.51       -0.31        0.01      0.0
2                     Percent Black     0.07        0.18        0.00      0.0
3       Percent Econ. Disadvantaged     0.58        0.10        0.01      0.0
4  Average STAAR Performance (Std.)     0.09       -0.53        0.03      0.0

In [17]:
dfs = [teacher, student]
rows = [15, 24]
tables.n_to_excel(file = table_path + 'DOI v. TPS v. Charter.xlsx',
                 col = 4, row = 4, n = len(data[data.distischarter == 1]))
for df, row in zip(dfs,rows):
    tables.var_diff_to_excel(file = table_path + 'DOI v. TPS v. Charter.xlsx', 
                             df = df, 
                             control_col = 'Control', 
                             diff_col = 'Difference', 
                             se_col = 'Std. Error', pvalue_col = 'P-value',
                             start_col = 2, start_row = row,
                             added_third_col = True)