In [28]:
import pandas as pd
import os
import statsmodels.formula.api as sm

import regulations
import analysis
import tables

In [29]:
data_path = '/Users/kylieleblancKylie/domino/dofis/data/'
table_path = '/Users/kylieleblancKylie/domino/dofis/results/'
data = pd.read_csv(os.path.join(data_path, 'clean', 'master_data.csv'),
                  sep=",")
data['cons'] = 1

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [30]:
data = data[data.year == 'yr1415']

# Student Performance

## Schedules

In [31]:
math_df = analysis.create_balance_df(data = data, list_of_regs = regulations.schedules,
                         reg_labels = regulations.labels, x_var = 'math')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = math_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 5)
math_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,25.0811 - Minimum First Day of Instruction,0.90,0.00,0.01,0.738431
1,25.081 - Minimum Minutes of Operation,0.41,-0.02,0.02,0.423447
2,25.0812 - Minimum Last Day of Instruction,0.29,-0.01,0.02,0.582178
3,25.082 - Pledge of Allegiance and Minute of Si...,0.21,-0.01,0.02,0.558455

In [32]:
reading_df = analysis.create_balance_df(data = data, list_of_regs = regulations.schedules,
                         reg_labels = regulations.labels, x_var = 'reading')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = reading_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 5, start_row = 5)
reading_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,25.0811 - Minimum First Day of Instruction,0.90,0.01,0.01,0.438708
1,25.081 - Minimum Minutes of Operation,0.41,-0.01,0.02,0.762016
2,25.0812 - Minimum Last Day of Instruction,0.29,-0.02,0.02,0.399463
3,25.082 - Pledge of Allegiance and Minute of Si...,0.21,-0.00,0.02,0.846330

## Class Size

In [33]:
math_df = analysis.create_balance_df(data = data, list_of_regs = regulations.class_size,
                         reg_labels = regulations.labels, x_var = 'math')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = math_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 14)
math_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,25.112 - Class Size Maximum,0.43,0.02,0.02,0.471853
1,25.113 - Notice of Class Size,0.36,0.03,0.02,0.186419
2,25.111 - Maximum Student Teacher Ratio,0.16,0.01,0.02,0.555057

In [34]:
reading_df = analysis.create_balance_df(data = data, list_of_regs = regulations.class_size,
                         reg_labels = regulations.labels, x_var = 'reading')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = reading_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 5, start_row = 14)
reading_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,25.112 - Class Size Maximum,0.43,0.03,0.02,0.285807
1,25.113 - Notice of Class Size,0.36,0.04,0.02,0.061669
2,25.111 - Maximum Student Teacher Ratio,0.16,0.00,0.02,0.781629

In [35]:
## Certification

In [36]:
math_df = analysis.create_balance_df(data = data, list_of_regs = regulations.certification,
                         reg_labels = regulations.labels, x_var = 'math')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = math_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 21)
math_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,21.003 - Teacher Certification Required,0.74,-0.02,0.02,0.472952
1,21.053 - Presentation of Teacher Certificates,0.29,-0.04,0.02,0.047244
2,21.057 - Notice of Uncertified Teacher,0.29,-0.02,0.02,0.294626

In [37]:
reading_df = analysis.create_balance_df(data = data, list_of_regs = regulations.certification,
                         reg_labels = regulations.labels, x_var = 'reading')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = reading_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 5, start_row = 21)
reading_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,21.003 - Teacher Certification Required,0.74,0.01,0.02,0.594763
1,21.053 - Presentation of Teacher Certificates,0.29,-0.02,0.02,0.303708
2,21.057 - Notice of Uncertified Teacher,0.29,-0.00,0.02,0.901877

In [38]:
## Contracts

In [39]:
math_df = analysis.create_balance_df(data = data, list_of_regs = regulations.contracts,
                         reg_labels = regulations.labels, x_var = 'math')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = math_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 28)
math_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,21.102 - Maximum Probationary Contract Length,0.39,-0.00,0.02,0.847024
1,21.401 - Minimum Service Days Required for Tea...,0.35,-0.05,0.02,0.045047
2,21.352 - Appraisal of Teachers,0.20,0.03,0.02,0.173893
3,21.354 - Principal Appriasal,0.07,0.02,0.01,0.091828

In [40]:
reading_df = analysis.create_balance_df(data = data, list_of_regs = regulations.contracts,
                         reg_labels = regulations.labels, x_var = 'reading')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = reading_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 5, start_row = 28)
reading_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,21.102 - Maximum Probationary Contract Length,0.38,0.02,0.02,0.509223
1,21.401 - Minimum Service Days Required for Tea...,0.35,-0.02,0.02,0.391484
2,21.352 - Appraisal of Teachers,0.19,0.04,0.02,0.031031
3,21.354 - Principal Appriasal,0.06,0.02,0.01,0.038780

In [41]:
## Student Behavior

In [42]:
math_df = analysis.create_balance_df(data = data, list_of_regs = regulations.behavior,
                         reg_labels = regulations.labels, x_var = 'math')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = math_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 3, start_row = 37)
math_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,25.092 - Minimum Attendance for Class Credit,0.27,-0.03,0.02,0.141912
1,37.0012 - Designation of Campus Behavior Coord...,0.22,-0.00,0.02,0.988860
2,25.036 - Transfers,0.19,-0.02,0.02,0.375891

In [43]:
reading_df = analysis.create_balance_df(data = data, list_of_regs = regulations.behavior,
                         reg_labels = regulations.labels, x_var = 'reading')
tables.var_diff_to_excel(file = table_path + 'Student Performance.xlsx', 
                         df = reading_df, 
                         control_col = 'Control', 
                         diff_col = 'Exemption Difference', 
                         se_col = 'Std. Error', pvalue_col = 'P-value',
                         start_col = 5, start_row = 37)
reading_df

,Regulation,Control,Exemption Difference,Std. Error,P-value
0,25.092 - Minimum Attendance for Class Credit,0.27,-0.04,0.02,0.055476
1,37.0012 - Designation of Campus Behavior Coord...,0.23,-0.01,0.02,0.535316
2,25.036 - Transfers,0.19,0.01,0.02,0.554961