In [1]:
import os
%matplotlib inline
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from start import data_path

In [2]:
data = pd.read_csv(os.path.join(data_path,'doi_dates_and_exemptions.csv'),
                  sep=",")
data = data[['title', 'link', 'date_year', 'date_phrase']]
data.head()

,title,link,date_year,date_phrase
0,Abbott ISD,https://www.abbottisd.org/ourpages/auto/2018/3...,2023.0,for the next five years (March 2018-February 2...
1,Abernathy ISD,https://1.cdn.edl.io/epGD4mZXjWUcPl8yA7IhlcDol...,2017.0,"the Texas Education Code. On Thursday, January..."
2,Abilene ISD,https://www.abileneisd.org/wp-content/uploads/...,2018.0,". The Committee met on December 14, 2017, Janu..."
3,Academy ISD,https://4.files.edl.io/1a8f/06/29/18/204245-44...,2017.0,2018-2019 school year and concluding at the en...
4,Adrian ISD,http://www.adrianisd.net/UserFiles/Servers/Ser...,2018.0,term of up to five years beginning June 2018 a...

In [3]:
data.to_csv(os.path.join(data_path,'fix_dates.csv'))

### Add column called correct. Put correct year in this column. Save as fix_dates_corrected.csv. Then upload.

In [4]:
#TODO move this to cleaning file
old_year = pd.read_csv(os.path.join(data_path,'doi_dates_and_exemptions.csv'), sep=",")
new_year = pd.read_csv(os.path.join(data_path, 'fix_dates_corrected.csv'), sep=",")
new_year = new_year[['title', 'correct']]
new_year = new_year.rename(columns = {'correct':'doi_year'})
new_year = new_year[['title', 'doi_year']]
new_year.head()

           title  doi_year
0     Abbott ISD      2018
1  Abernathy ISD      2017
2    Abilene ISD      2018
3    Academy ISD      2018
4     Adrian ISD      2018

In [7]:
data = old_year.merge(new_year, left_on = 'title', right_on = 'title', how = 'left')
data.to_csv(os.path.join(data_path,'doi_dates_and_exemptions.csv'),
                  sep=",")
data.head()

,title,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,level,type,link,text,p_innovation,...,term_p,finalize_year,finalize_month,finalize_phrase,finalize_p,date_year,date_month,date_phrase,date_ay,doi_year
0,Abbott ISD,780.0,2481.0,2481,2481,Second,pdf,https://www.abbottisd.org/ourpages/auto/2018/3...,1 Abbott Independent School District District ...,0.999949,...,0.987736,2018,February,Abbott Independent School District District of...,0.955832,2023.0,March,for the next five years (March 2018-February 2...,2022.0,2018.0
1,Abernathy ISD,779.0,871.0,871,871,Second,pdf,https://1.cdn.edl.io/epGD4mZXjWUcPl8yA7IhlcDol...,Abernathy ISD District of Innovation Plan â€“ Dr...,0.998340,...,0.025909,2017,January,"the Texas Education Code. On Thursday, January...",0.999955,2017.0,January,"the Texas Education Code. On Thursday, January...",2016.0,2017.0
2,Abilene ISD,778.0,85.0,85,85,First,pdf,https://www.abileneisd.org/wp-content/uploads/...,0 ABILENE INDEPENDENT SCHOOL DISTRICT Local In...,0.999955,...,0.846878,2018,April,". The Committee met on December 14, 2017, Janu...",0.999955,2018.0,April,". The Committee met on December 14, 2017, Janu...",2018.0,2018.0
3,Academy ISD,777.0,2845.0,2845,2845,Second,docx,https://4.files.edl.io/1a8f/06/29/18/204245-44...,District of Innovation Plan Developed in coope...,0.999836,...,0.999955,2018,June,"regularly scheduled board meeting on June 28, ...",0.999955,2017.0,NaN,2018-2019 school year and concluding at the en...,2017.0,2018.0
4,Adrian ISD,776.0,169.0,169,169,First,pdf,http://www.adrianisd.net/UserFiles/Servers/Ser...,Adrian ISD District of Innovation Plan House B...,0.999945,...,0.999955,-999,NaN,NaN,0.000000,2018.0,June,term of up to five years beginning June 2018 a...,2018.0,2018.0