In [1]:
import pandas as pd
import os

from library import regulations
from library import analysis
from library import tables

In [2]:
data_path = '/Users/kylieleblancKylie/domino/dofis/data/'
table_path = '/Users/kylieleblancKylie/domino/dofis/results/descriptive/'
data = pd.read_csv(os.path.join(data_path, 'clean', 'master_data.csv'),
                  sep=",")

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data = data[data.year == 'yr1415']

# Geography

In [4]:
columns = ['Count', 'Percent Urban', 'Percent Suburban', 'Percent Town', 'Percent Rural', 'F-test p-value']

In [5]:
schedules_df = analysis.create_count_proportion_df(data, list_of_regs = regulations.schedules, 
                                                dict_of_reg_labels = regulations.labels)
tables.df_to_excel(file = table_path + 'Geography.xlsx', df = schedules_df,
                  df_columns = columns, start_row = 4, start_col = 3)
schedules_df

,Regulation,Count,Percent Urban,Percent Suburban,Percent Town,Percent Rural,F-test p-value
0,25.0811 - Minimum First Day of Instruction,709,0.92,0.88,0.92,0.90,0.54
1,25.081 - Minimum Minutes of Operation,324,0.46,0.38,0.35,0.47,0.02
2,25.0812 - Minimum Last Day of Instruction,226,0.26,0.26,0.26,0.33,0.22
3,25.082 - Pledge of Allegiance and Minute of Si...,161,0.23,0.14,0.19,0.24,0.05

In [6]:
class_size_df = analysis.create_count_proportion_df(data, list_of_regs = regulations.class_size,
                                                 dict_of_reg_labels = regulations.labels)
tables.df_to_excel(file = table_path + 'Geography.xlsx', df = class_size_df,
                  df_columns = columns, start_row = 9, start_col = 3)
class_size_df

,Regulation,Count,Percent Urban,Percent Suburban,Percent Town,Percent Rural,F-test p-value
0,25.112 - Class Size Maximum,339,0.36,0.43,0.48,0.41,0.34
1,25.113 - Notice of Class Size,285,0.33,0.35,0.39,0.35,0.76
2,25.111 - Maximum Student Teacher Ratio,126,0.23,0.18,0.16,0.14,0.47

In [7]:
certification_df = analysis.create_count_proportion_df(data, 
                                                 list_of_regs = regulations.certification, 
                                                 dict_of_reg_labels = regulations.labels)
tables.df_to_excel(file = table_path + 'Geography.xlsx', df = certification_df,
                  df_columns = columns, start_row = 13, start_col = 3)
certification_df

,Regulation,Count,Percent Urban,Percent Suburban,Percent Town,Percent Rural,F-test p-value
0,21.003 - Teacher Certification Required,581,0.69,0.68,0.78,0.75,0.07
1,21.053 - Presentation of Teacher Certificates,225,0.26,0.24,0.31,0.30,0.47
2,21.057 - Notice of Uncertified Teacher,227,0.28,0.24,0.30,0.31,0.48

In [8]:
contracts_df = analysis.create_count_proportion_df(data, 
                                                 list_of_regs = regulations.contracts, 
                                                 dict_of_reg_labels = regulations.labels)
tables.df_to_excel(file = table_path + 'Geography.xlsx', df = contracts_df,
                  df_columns = columns, start_row = 17, start_col = 3)
contracts_df

,Regulation,Count,Percent Urban,Percent Suburban,Percent Town,Percent Rural,F-test p-value
0,21.102 - Maximum Probationary Contract Length,303,0.13,0.30,0.43,0.43,0.00
1,21.401 - Minimum Service Days Required for Tea...,270,0.08,0.15,0.27,0.53,0.00
2,21.352 - Appraisal of Teachers,157,0.23,0.22,0.22,0.18,0.53
3,21.354 - Principal Appriasal,54,0.08,0.09,0.05,0.07,0.54

In [9]:
behavior_df = analysis.create_count_proportion_df(data, 
                                                 list_of_regs = regulations.behavior, 
                                                 dict_of_reg_labels = regulations.labels)
tables.df_to_excel(file = table_path + 'Geography.xlsx', df = behavior_df,
                  df_columns = columns, start_row = 22, start_col = 3)
behavior_df

,Regulation,Count,Percent Urban,Percent Suburban,Percent Town,Percent Rural,F-test p-value
0,25.092 - Minimum Attendance for Class Credit,211,0.49,0.37,0.27,0.19,0.0
1,37.0012 - Designation of Campus Behavior Coord...,176,0.38,0.27,0.29,0.14,0.0
2,25.036 - Transfers,150,0.05,0.06,0.20,0.27,0.0