In [1]:
import sys
sys.path.append("../")


import os
%matplotlib inline
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from patsy import dmatrices
from openpyxl import load_workbook
import engarde.decorators as ed

from linearmodels import PanelOLS

from library import test_data
@ed.verify(test_data.allyearsandtpsd)
@ed.verify(test_data.alldois)
def load(data):
    return data

from library import print_statistics

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/panel/data.py:10: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import (Categorical, DataFrame, Index, MultiIndex, Panel, Series,

In [2]:
def coef_with_stars(coef, pvalue):
    if pvalue >.05:
        coef = str(coef)
    if pvalue <= .05:
        coef = str(coef) + '*'
    if pvalue <= .01:
        coef = coef + '*'
    if pvalue <= .001:
        coef = coef + '*'
    return(coef)
test = coef_with_stars(.1, .005)

In [3]:
data_path = '/Users/kylieleblancKylie/domino/dofis/data/'
table_path = '/Users/kylieleblancKylie/domino/dofis/results/impact/'
data = pd.read_csv(os.path.join(data_path, 'clean', 'gdid.csv'),
                  sep=",", low_memory= False)
#load(data)
data.tail()
print(data[data.doi == True].district.nunique())
data = data[data.doi == True]
data.sample()

822

,Unnamed: 0,year,campus,campname,campischarter,district,distname,distischarter,rating_academic,rating_financial,...,type_urban,type_suburban,type_town,type_rural,eligible,teachers_nodegree,teachers_badegree,teachers_msdegree,teachers_phddegree,treatpost
13984,13984,2013,126901001,ALVARADO H S,N,126901,ALVARADO ISD,N,M,NaN,...,0,1,0,0,1,NaN,NaN,NaN,NaN,False

In [4]:
data['yearpost'] = data.year - data.doi_year
data.yearpost.value_counts()

 0.0    6346
-1.0    6329
-2.0    6293
-3.0    6275
-4.0    6263
 1.0    6129
-5.0    5356
 2.0    5190
-6.0    1152
 3.0     938
-7.0     201
Name: yearpost, dtype: int64

In [5]:
#convert year to datetime
df = data.reset_index()
df['year'] = pd.to_datetime(df['year'], format='%Y')
#add column year to index
df = data.set_index(['year', 'campus'])
#swap indexes
df.index = df.index.swaplevel(0,1)
df[['district', 'doi_year','treatpost',]].tail(5)

                district  doi_year  treatpost
campus    year
253901105 2019    253901    2018.0       True
253901106 2019    253901    2018.0       True
253901107 2019    253901    2018.0       True
254902001 2019    254902    2018.0       True
254902101 2019    254902    2018.0       True

In [6]:
mod = PanelOLS.from_formula('sec_reading ~ + 1 + treatpost + students_hisp + students_num + TimeEffects + EntityEffects', df)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:            sec_reading   R-squared:                        0.0101
Estimator:                   PanelOLS   R-squared (Between):              0.1714
No. Observations:               23605   R-squared (Within):               0.0063
Date:                Mon, Oct 28 2019   R-squared (Overall):              0.1540
Time:                        13:54:06   Log-likelihood                   -5404.5
Cov. Estimator:             Clustered
                                        F-statistic:                      69.176
Entities:                        3349   P-value                           0.0000
Avg Obs:                       7.0484   Distribution:                 F(3,20246)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             17.179
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(3,20246)
Avg Obs:                       2950.6
Min Obs:                       2880.0
Max Obs:                       2991.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.1802     0.0736     2.4482     0.0144      0.0359      0.3245
treatpost[T.True]    -0.0118     0.0138    -0.8585     0.3906     -0.0389      0.0152
students_hisp        -0.7577     0.1441    -5.2588     0.0000     -1.0401     -0.4753
students_num          0.0003  5.608e-05     4.8163     0.0000      0.0002      0.0004
=====================================================================================

F-test for Poolability: 36.065
P-value: 0.0000
Distribution: F(3355,20246)

Included effects: Entity, Time

# Heterogenous effects

In [7]:
### Generate variable for number of hispanic students in year before the district declares

In [8]:
data.teachers_turnover_ratio_d

3         8.1740
4        10.8636
5        10.8636
6        10.8636
7        10.8636
          ...
69234     9.8000
69235     9.8000
69236     9.8000
69242    30.4000
69243    30.4000
Name: teachers_turnover_ratio_d, Length: 50951, dtype: float64

In [9]:
data_pre = data.loc[data.yearpost == -1]
data_pre = data_pre.rename(columns = {'students_hisp': 'students_hisp_pre',
                                     'teachers_turnover_ratio_d': 'teacher_turnover_pre'})
data_pre['low_avescores_pre'] = np.where(data_pre.avescores < data_pre.avescores.quantile(.25),1, 0)
data_pre['high_avescores_pre'] = np.where(data_pre.avescores > data_pre.avescores.quantile(.75),1,0)
data_pre = data_pre[['campus','students_hisp_pre', 'teacher_turnover_pre', 'low_avescores_pre', 'high_avescores_pre']]
data_hte = data.merge(data_pre, on = 'campus', how = 'left')
data_hte['majority_hisp_pre'] = np.where(data_hte.students_hisp_pre > .6, 1, 0)
data_hte['high_turnover'] = np.where(data_hte.teacher_turnover_pre > 20, 1, 0)
data_hte

,Unnamed: 0,year,campus,campname,campischarter,district,distname,distischarter,rating_academic,rating_financial,...,teachers_msdegree,teachers_phddegree,treatpost,yearpost,students_hisp_pre,teacher_turnover_pre,low_avescores_pre,high_avescores_pre,majority_hisp_pre,high_turnover
0,3,2012,109901001,ABBOTT SCHOOL,N,109901,ABBOTT ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.127208,16.5,0.0,1.0,0,0
1,4,2012,95901003,ABERNATHY DAEP,N,95901,ABERNATHY ISD,N,NaN,NaN,...,NaN,NaN,False,-5.0,1.000000,13.5,0.0,0.0,1,0
2,5,2012,95901101,ABERNATHY EL,N,95901,ABERNATHY ISD,N,NaN,NaN,...,NaN,NaN,False,-5.0,0.620596,13.5,0.0,0.0,1,0
3,6,2012,95901001,ABERNATHY H S,N,95901,ABERNATHY ISD,N,NaN,NaN,...,NaN,NaN,False,-5.0,0.495370,13.5,0.0,0.0,0,0
4,7,2012,95901041,ABERNATHY J H,N,95901,ABERNATHY ISD,N,NaN,NaN,...,NaN,NaN,False,-5.0,0.567708,13.5,0.0,1.0,0,0
5,8,2012,221901001,ABILENE H S,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.458668,13.1,0.0,0.0,0,0
6,9,2012,221901010,ACADEMY FOR TECHNOLOGY ENGINEERING,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.379501,13.1,0.0,0.0,0,0
7,10,2012,221901142,ACADIA ABILENE BEHAVIORAL HEALTH,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.428571,13.1,0.0,0.0,0,0
8,11,2012,221901102,AUSTIN EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.336134,13.1,0.0,1.0,0,0
9,12,2012,221901153,BASSETTI EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.372624,13.1,0.0,0.0,0,0
10,13,2012,221901103,BONHAM EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.415094,13.1,0.0,0.0,0,0
11,14,2012,221901104,BOWIE EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.456294,13.1,0.0,0.0,0,0
12,15,2012,221901047,CLACK MIDDLE,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.379224,13.1,0.0,0.0,0,0
13,16,2012,221901106,COLLEGE HEIGHTS EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,NaN,NaN,NaN,NaN,0,0
14,17,2012,221901002,COOPER H S,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.364932,13.1,0.0,0.0,0,0
15,18,2012,221901048,CRAIG MIDDLE,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.445493,13.1,0.0,0.0,0,0
16,19,2012,221901208,DAY NURSERY OF ABILENE,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.442308,13.1,0.0,0.0,0,0
17,20,2012,221901108,DYESS EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.289091,13.1,0.0,1.0,0,0
18,21,2012,221901110,FANNIN EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,NaN,NaN,NaN,NaN,0,0
19,22,2012,221901112,JACKSON EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.295495,13.1,0.0,0.0,0,0
20,23,2012,221901006,JEFFERSON OPPORTUNITY CTR,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.714286,13.1,1.0,0.0,1,0
21,24,2012,221901113,JOHNSTON EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.539143,13.1,0.0,0.0,0,0
22,25,2012,221901008,JUVENILE DETENTION CENTER,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.545455,13.1,0.0,0.0,0,0
23,26,2012,221901116,LEE EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.417308,13.1,1.0,0.0,0,0
24,27,2012,221901117,LOCUST ECC,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.393586,13.1,0.0,0.0,0,0
25,28,2012,221901118,LONG EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,NaN,NaN,NaN,NaN,0,0
26,29,2012,221901044,MADISON MIDDLE,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.410845,13.1,0.0,0.0,0,0
27,30,2012,221901045,MANN MIDDLE,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.557629,13.1,0.0,0.0,0,0
28,31,2012,221901152,ORTIZ EL,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.682663,13.1,1.0,0.0,1,0
29,32,2012,221901154,REAGAN EARLY CHILDHOOD,N,221901,ABILENE ISD,N,NaN,NaN,...,NaN,NaN,False,-6.0,0.257143,13.1,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50921,69203,2019,250904001,QUITMAN H S,N,250904,QUITMAN ISD,N,B,Pass,...,0.167203,0.000000,True,1.0,0.166667,19.8,1.0,0.0,0,0
50922,69204,2019,250904041,QUITMAN J H,N,250904,QUITMAN ISD,N,B,Pass,...,0.171806,0.000000,True,1.0,0.154982,19.8,0.0,0.0,0,0
50923,69205,2019,250904101,QUITMAN EL,N,250904,QUITMAN ISD,N,B,Pass,...,0.217391,0.000000,True,1.0,0.168260,19.8,0.0,1.0,0,0
50924,69206,2019,250905001,YANTIS SCHOOL,N,250905,YANTIS ISD,N,D,Pass,...,0.324675,0.000000,True,2.0,0.197368,21.1,0.0,0.0,0,1
50925,69207,2019,250905101,YANTIS EL,N,250905,YANTIS ISD,N,D,Pass,...,0.294118,0.000000,True,2.0,0.297170,21.1,0.0,0.0,0,1
50926,69211,2019,250907001,WINNSBORO H S,N,250907,WINNSBORO ISD,N,B,Pass,...,0.171254,0.000000,True,1.0,0.145740,20.5,0.0,0.0,0,1
50927,69212,2019,250907041,MEMORIAL MIDDLE,N,250907,WINNSBORO ISD,N,B,Pass,...,0.228261,0.000000,True,1.0,0.141921,20.5,0.0,0.0,0,1
50928,69213,2019,250907103,WINNSBORO EL,N,250907,WINNSBORO ISD,N,B,Pass,...,0.025000,0.000000,True,1.0,0.164103,20.5,0.0,0.0,0,1
50929,69214,2019,251901001,DENVER CITY H S,N,251901,DENVER CITY ISD,N,B,Pass,...,0.238806,0.000000,True,2.0,0.754352,13.5,0.0,0.0,1,0
50930,69215,2019,251901041,WILLIAM G GRAVITT J H,N,251901,DENVER CITY ISD,N,B,Pass,...,0.080153,0.000000,True,2.0,0.788136,13.5,0.0,0.0,1,0
50931,69216,2019,251901101,KELLEY EL,N,251901,DENVER CITY ISD,N,B,Pass,...,0.197952,0.000000,True,2.0,0.813472,13.5,0.0,0.0,1,0
50932,69217,2019,251901104,DODSON PRI,N,251901,DENVER CITY ISD,N,B,Pass,...,0.277580,0.000000,True,2.0,0.822519,13.5,0.0,0.0,1,0
50933,69221,2019,252901001,GRAHAM H S,N,252901,GRAHAM ISD,N,C,Pass,...,0.223340,0.000000,True,2.0,0.261561,14.4,0.0,0.0,0,0
50934,69222,2019,252901002,GRAHAM LEARNING CTR,N,252901,GRAHAM ISD,N,C,Pass,...,0.000000,0.000000,True,2.0,0.263158,14.4,0.0,0.0,0,0
50935,69223,2019,252901041,GRAHAM J H,N,252901,GRAHAM ISD,N,C,Pass,...,0.229592,0.000000,True,2.0,0.292948,14.4,0.0,0.0,0,0
50936,69224,2019,252901101,CRESTVIEW EL,N,252901,GRAHAM ISD,N,C,Pass,...,0.084270,0.000000,True,2.0,0.331560,14.4,0.0,0.0,0,0
50937,69225,2019,252901104,PIONEER EL,N,252901,GRAHAM ISD,N,C,Pass,...,0.055556,0.000000,True,2.0,0.357977,14.4,0.0,0.0,0,0
50938,69226,2019,252901105,WOODLAND EL,N,252901,GRAHAM ISD,N,C,Pass,...,0.078431,0.000000,True,2.0,0.346479,14.4,0.0,0.0,0,0
50939,69227,2019,252902002,NEWCASTLE SCHOOL,N,252902,NEWCASTLE ISD,N,Met Standard,Pass,...,0.216216,0.000000,True,2.0,0.104803,10.0,0.0,0.0,0,0
50940,69228,2019,252903001,OLNEY H S,N,252903,OLNEY ISD,N,A,Pass,...,0.340502,0.000000,True,2.0,0.357895,25.1,0.0,0.0,0,1
50941,69229,2019,252903041,OLNEY J H,N,252903,OLNEY ISD,N,A,Pass,...,0.274809,0.022901,True,2.0,0.462585,25.1,0.0,0.0,0,1
50942,69230,2019,252903101,OLNEY EL,N,252903,OLNEY ISD,N,A,Pass,...,0.085294,0.000000,True,2.0,0.351429,25.1,0.0,1.0,0,1
50943,69231,2019,253901001,ZAPATA H S,N,253901,ZAPATA COUNTY ISD,N,B,Pass,...,0.162252,0.000000,True,1.0,0.989496,7.5,1.0,0.0,1,0
50944,69232,2019,253901041,ZAPATA MIDDLE,N,253901,ZAPATA COUNTY ISD,N,B,Pass,...,0.101215,0.000000,True,1.0,0.987968,7.5,1.0,0.0,1,0
50945,69233,2019,253901101,BENAVIDES EL,N,253901,ZAPATA COUNTY ISD,N,B,Pass,...,0.000000,0.000000,True,1.0,1.000000,7.5,0.0,0.0,1,0
50946,69234,2019,253901105,ZAPATA NORTH EL,N,253901,ZAPATA COUNTY ISD,N,B,Pass,...,0.083333,0.000000,True,1.0,0.995290,7.5,1.0,0.0,1,0
50947,69235,2019,253901106,ZAPATA SOUTH EL,N,253901,ZAPATA COUNTY ISD,N,B,Pass,...,0.058824,0.000000,True,1.0,0.986711,7.5,1.0,0.0,1,0
50948,69236,2019,253901107,FIDEL AND ANDREA R VILLARREAL EL,N,253901,ZAPATA COUNTY ISD,N,B,Pass,...,0.125000,0.000000,True,1.0,0.998131,7.5,1.0,0.0,1,0
50949,69242,2019,254902001,LA PRYOR H S,N,254902,LA PRYOR ISD,N,C,Pass,...,0.227848,0.000000,True,1.0,0.941176,29.2,1.0,0.0,1,1
50950,69243,2019,254902101,LA PRYOR EL,N,254902,LA PRYOR ISD,N,C,Pass,...,0.010050,0.000000,True,1.0,0.926641,29.2,0.0,0.0,1,1

In [10]:
data_pre = data.loc[data.year == 2016]
data_pre['rural_pre'] = np.where(data_pre.type_description == "RURAL", 1, 0)
data_pre['urban_pre'] = np.where(data_pre.type_description == "URBAN", 1, 0)
data_pre = data_pre[['campus','rural_pre', 'urban_pre']]
data_hte = data_hte.merge(data_pre, on = 'campus', how = 'left')
#df_hte[['students_hisp', 'students_hisp_pre', 'yearpost']].sample(5)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [11]:
#convert year to datetime
df_hte = data_hte.reset_index()
df_hte['year'] = pd.to_datetime(df_hte['year'], format='%Y')
#add column year to index
df_hte = data_hte.set_index(['year', 'campus'])
#swap indexes
df_hte.index = df_hte.index.swaplevel(0,1)
df_hte[['district', 'doi_year','treatpost',]].tail(20)

                district  doi_year  treatpost
campus    year
251901101 2019    251901    2017.0       True
251901104 2019    251901    2017.0       True
252901001 2019    252901    2017.0       True
252901002 2019    252901    2017.0       True
252901041 2019    252901    2017.0       True
252901101 2019    252901    2017.0       True
252901104 2019    252901    2017.0       True
252901105 2019    252901    2017.0       True
252902002 2019    252902    2017.0       True
252903001 2019    252903    2017.0       True
252903041 2019    252903    2017.0       True
252903101 2019    252903    2017.0       True
253901001 2019    253901    2018.0       True
253901041 2019    253901    2018.0       True
253901101 2019    253901    2018.0       True
253901105 2019    253901    2018.0       True
253901106 2019    253901    2018.0       True
253901107 2019    253901    2018.0       True
254902001 2019    254902    2018.0       True
254902101 2019    254902    2018.0       True

# Majority Hispanic

In [12]:
df_hte['treatpost_hisp'] = df_hte.treatpost * df_hte.majority_hisp_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_hisp + students_hisp + students_num + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0097
Estimator:                   PanelOLS   R-squared (Between):              0.0984
No. Observations:               45633   R-squared (Within):              -0.0307
Date:                Mon, Oct 28 2019   R-squared (Overall):              0.0849
Time:                        13:54:23   Log-likelihood                   -4213.0
Cov. Estimator:             Clustered
                                        F-statistic:                      96.672
Entities:                        6088   P-value                           0.0000
Avg Obs:                       7.4956   Distribution:                 F(4,39534)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             30.607
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(4,39534)
Avg Obs:                       5704.1
Min Obs:                       5558.0
Max Obs:                       5792.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.2376     0.0495     4.7987     0.0000      0.1405      0.3346
treatpost[T.True]    -0.0567     0.0097    -5.8124     0.0000     -0.0758     -0.0375
treatpost_hisp        0.1013     0.0121     8.3963     0.0000      0.0776      0.1249
students_hisp        -0.4476     0.0943    -4.7458     0.0000     -0.6324     -0.2627
students_num          0.0002  3.917e-05     4.5810     0.0000      0.0001      0.0003
=====================================================================================

F-test for Poolability: 53.439
P-value: 0.0000
Distribution: F(6094,39534)

Included effects: Entity, Time

In [28]:
df_hte['treatpost_hisp'] = df_hte.treatpost * df_hte.majority_hisp_pre
df_hte['treatpost_hisp_rural'] = df_hte.treatpost_hisp * df_hte.rural_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_hisp + treatpost_hisp_rural + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0054
Estimator:                   PanelOLS   R-squared (Between):             -0.0102
No. Observations:               45033   R-squared (Within):              -0.0242
Date:                Mon, Oct 28 2019   R-squared (Overall):             -0.0119
Time:                        14:00:33   Log-likelihood                   -4403.5
Cov. Estimator:             Clustered
                                        F-statistic:                      70.884
Entities:                        5844   P-value                           0.0000
Avg Obs:                       7.7059   Distribution:                 F(3,39179)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             25.803
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(3,39179)
Avg Obs:                       5629.1
Min Obs:                       5433.0
Max Obs:                       5734.0

                                  Parameter Estimates
========================================================================================
                      Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
----------------------------------------------------------------------------------------
Intercept                0.1535     0.0022     68.747     0.0000      0.1492      0.1579
treatpost[T.True]       -0.0563     0.0098    -5.7244     0.0000     -0.0756     -0.0370
treatpost_hisp           0.1002     0.0123     8.1354     0.0000      0.0761      0.1244
treatpost_hisp_rural    -0.0264     0.0457    -0.5770     0.5639     -0.1160      0.0632
========================================================================================

F-test for Poolability: 65.137
P-value: 0.0000
Distribution: F(5850,39179)

Included effects: Entity, Time

In [27]:
df_hte[df_hte.majority_hisp_pre == 1][['district', 'type_description', 'majority_hisp_pre']]

                district             type_description  majority_hisp_pre
campus    year
95901003  2012     95901                        RURAL                  1
95901101  2012     95901                        RURAL                  1
221901006 2012    221901           OTHER CENTRAL CITY                  1
221901152 2012    221901           OTHER CENTRAL CITY                  1
221901125 2012    221901           OTHER CENTRAL CITY                  1
...                  ...                          ...                ...
253901105 2019    253901  OTHER CENTRAL CITY SUBURBAN                  1
253901106 2019    253901  OTHER CENTRAL CITY SUBURBAN                  1
253901107 2019    253901  OTHER CENTRAL CITY SUBURBAN                  1
254902001 2019    254902                        RURAL                  1
254902101 2019    254902                        RURAL                  1

[15956 rows x 3 columns]

# Rural

In [13]:
df_hte['treatpost_rural'] = df_hte.treatpost * df_hte.rural_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_rural + rural_pre +  students_hisp + students_num  + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

AbsorbingEffectError:
The model cannot be estimated. The included effects have fully absorbed
one or more of the variables. This occurs when one or more of the dependent
variable is perfectly explained using the effects included in the model.

The following variables or variable combinations have been fully absorbed
or have become perfectly collinear after effects are removed:

          Intercept, rural_pre

Set drop_absorbed=True to automatically drop absorbed variables.

# Performance

In [76]:
df_hte['treatpost_low'] = df_hte.treatpost * df_hte.low_avescores_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_low + students_hisp + students_num  + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0055
Estimator:                   PanelOLS   R-squared (Between):              0.1075
No. Observations:               44625   R-squared (Within):              -0.0371
Date:                Tue, Oct 15 2019   R-squared (Overall):              0.0922
Time:                        10:59:37   Log-likelihood                   -4385.5
Cov. Estimator:             Clustered
                                        F-statistic:                      53.286
Entities:                        5795   P-value                           0.0000
Avg Obs:                       7.7006   Distribution:                 F(4,38819)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             14.691
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(4,38819)
Avg Obs:                       5578.1
Min Obs:                       5388.0
Max Obs:                       5670.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.2742     0.0502     5.4617     0.0000      0.1758      0.3727
treatpost[T.True]    -0.0367     0.0097    -3.8074     0.0001     -0.0557     -0.0178
treatpost_low         0.0463     0.0131     3.5450     0.0004      0.0207      0.0719
students_hisp        -0.4947     0.0954    -5.1845     0.0000     -0.6818     -0.3077
students_num          0.0002  4.004e-05     4.0220     0.0001   8.257e-05      0.0002
=====================================================================================

F-test for Poolability: 50.885
P-value: 0.0000
Distribution: F(5801,38819)

Included effects: Entity, Time

In [77]:
df_hte['treatpost_high'] = df_hte.treatpost * df_hte.high_avescores_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_high+ students_hisp + students_num  + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0045
Estimator:                   PanelOLS   R-squared (Between):              0.1131
No. Observations:               44625   R-squared (Within):              -0.0372
Date:                Tue, Oct 15 2019   R-squared (Overall):              0.0979
Time:                        10:59:39   Log-likelihood                   -4406.3
Cov. Estimator:             Clustered
                                        F-statistic:                      44.207
Entities:                        5795   P-value                           0.0000
Avg Obs:                       7.7006   Distribution:                 F(4,38819)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             12.016
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(4,38819)
Avg Obs:                       5578.1
Min Obs:                       5388.0
Max Obs:                       5670.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.2814     0.0502     5.6027     0.0000      0.1829      0.3798
treatpost[T.True]    -0.0225     0.0098    -2.2994     0.0215     -0.0417     -0.0033
treatpost_high       -0.0090     0.0118    -0.7622     0.4459     -0.0322      0.0142
students_hisp        -0.5011     0.0955    -5.2492     0.0000     -0.6882     -0.3140
students_num          0.0002  4.029e-05     3.8354     0.0001   7.556e-05      0.0002
=====================================================================================

F-test for Poolability: 48.428
P-value: 0.0000
Distribution: F(5801,38819)

Included effects: Entity, Time

# Teacher Turnover

In [78]:
df_hte['treatpost_turnover'] = df_hte.treatpost * df_hte.high_turnover
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_turnover + students_hisp + students_num + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0049
Estimator:                   PanelOLS   R-squared (Between):              0.1116
No. Observations:               45633   R-squared (Within):              -0.0331
Date:                Tue, Oct 15 2019   R-squared (Overall):              0.0985
Time:                        11:00:01   Log-likelihood                   -4324.1
Cov. Estimator:             Clustered
                                        F-statistic:                      48.184
Entities:                        6088   P-value                           0.0000
Avg Obs:                       7.4956   Distribution:                 F(4,39534)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             13.505
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(4,39534)
Avg Obs:                       5704.1
Min Obs:                       5558.0
Max Obs:                       5792.0

                                 Parameter Estimates
======================================================================================
                    Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------
Intercept              0.2770     0.0497     5.5698     0.0000      0.1795      0.3745
treatpost[T.True]     -0.0294     0.0095    -3.0907     0.0020     -0.0481     -0.0108
treatpost_turnover     0.0324     0.0134     2.4158     0.0157      0.0061      0.0587
students_hisp         -0.4981     0.0943    -5.2800     0.0000     -0.6831     -0.3132
students_num           0.0002  3.982e-05     3.8652     0.0001   7.586e-05      0.0002
======================================================================================

F-test for Poolability: 52.471
P-value: 0.0000
Distribution: F(6094,39534)

Included effects: Entity, Time