In [17]:
import sys
sys.path.append("../")


import os
%matplotlib inline
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
from patsy import dmatrices
from openpyxl import load_workbook
import engarde.decorators as ed

from linearmodels import PanelOLS

from library import test_data
@ed.verify(test_data.allyearsandtpsd)
@ed.verify(test_data.alldois)
def load(data):
    return data

from library import print_statistics

In [18]:
def coef_with_stars(coef, pvalue):
    if pvalue >.05:
        coef = str(coef)
    if pvalue <= .05:
        coef = str(coef) + '*'
    if pvalue <= .01:
        coef = coef + '*'
    if pvalue <= .001:
        coef = coef + '*'
    return(coef)
test = coef_with_stars(.1, .005)

In [19]:
data_path = '/Users/kylieleblancKylie/domino/dofis/data/'
table_path = '/Users/kylieleblancKylie/domino/dofis/results/impact/'
data = pd.read_csv(os.path.join(data_path, 'clean', 'gdid.csv'),
                  sep=",", low_memory= False)
#load(data)
data.tail()
print(data[data.doi == True].district.nunique())
data = data[data.doi == True]
data.sample()

824

,Unnamed: 0,year,campus,campname,campischarter,district,distname,distischarter,rating_academic,rating_financial,...,type_urban,type_suburban,type_town,type_rural,eligible,teachers_nodegree,teachers_badegree,teachers_msdegree,teachers_phddegree,treatpost
31908,31908,2015,169901041,BOWIE J H,N,169901,BOWIE ISD,N,M,Pass,...,0,0,1,0,1,0.0,0.843416,0.156584,0.0,False

In [20]:
list(data.columns)

['Unnamed: 0',
 'year',
 'campus',
 'campname',
 'campischarter',
 'district',
 'distname',
 'distischarter',
 'rating_academic',
 'rating_financial',
 'rating_academic_c',
 'type',
 'type_description',
 'cntyname_c',
 'students_amind_num',
 'students_asian_num',
 'students_black_num',
 'students_frpl_num',
 'students_hisp_num',
 'students_num',
 'students_paci_num',
 'students_tworaces_num',
 'students_white_num',
 'teachers_badegree_num',
 'teachers_exp_ave',
 'teachers_msdegree_num',
 'teachers_new_num',
 'teachers_nodegree_num',
 'teachers_num',
 'teachers_phddegree_num',
 'teachers_tenure_ave',
 'alg_avescore',
 'bio_avescore',
 'eng1_avescore',
 'eng2_avescore',
 'm_3rd_avescore',
 'm_4th_avescore',
 'm_5th_avescore',
 'm_6th_avescore',
 'm_7th_avescore',
 'm_8th_avescore',
 'r_3rd_avescore',
 'r_4th_avescore',
 'r_5th_avescore',
 'r_6th_avescore',
 'r_7th_avescore',
 'r_8th_avescore',
 's_8th_avescore',
 'us_avescore',
 'alg_numtakers',
 'bio_numtakers',
 'eng1_numtakers',
 'eng2_numtakers',
 'm_3rd_numtakers',
 'm_4th_numtakers',
 'm_5th_numtakers',
 'm_6th_numtakers',
 'm_7th_numtakers',
 'm_8th_numtakers',
 'r_3rd_numtakers',
 'r_4th_numtakers',
 'r_5th_numtakers',
 'r_6th_numtakers',
 'r_7th_numtakers',
 'r_8th_numtakers',
 's_8th_numtakers',
 'us_numtakers',
 'days_max',
 'days_mean',
 'days_min',
 'class_size_1',
 'class_size_2',
 'class_size_3',
 'class_size_4',
 'class_size_5',
 'class_size_6',
 'class_size_k',
 'class_size_sec_lang',
 'class_size_sec_math',
 'class_size_sec_r',
 'class_size_sec_sci',
 'class_size_sec_ss',
 'stu_teach_ratio',
 'Unnamed: 0_x',
 'link',
 'p_doi',
 'doi_year',
 'total',
 '_merge_x',
 'doi',
 'Unnamed: 0_y',
 '_merge_y',
 'cert_area_elem',
 'cert_area_voc',
 'cert_secondary_ela',
 'cert_secondary_math',
 'cert_secondary_sci',
 'certification',
 'vocational',
 'county',
 'cnty_pop',
 'students_frpl',
 'students_black',
 'students_hisp',
 'students_white',
 'students_teacher_ratio',
 'r_3rd_std',
 'm_3rd_std',
 'r_4th_std',
 'm_4th_std',
 'r_5th_std',
 'm_5th_std',
 'r_6th_std',
 'm_6th_std',
 'r_7th_std',
 'm_7th_std',
 'r_8th_std',
 'm_8th_std',
 's_8th_std',
 'alg_std',
 'bio_std',
 'eng1_std',
 'eng2_std',
 'us_std',
 'elem_math',
 'elem_reading',
 'elem',
 'sec_math',
 'sec_reading',
 'sec_science',
 'avescores',
 'geography',
 'charter',
 'district_status',
 'type_urban',
 'type_suburban',
 'type_town',
 'type_rural',
 'eligible',
 'teachers_nodegree',
 'teachers_badegree',
 'teachers_msdegree',
 'teachers_phddegree',
 'treatpost']

In [21]:
data['yearpost'] = data.year - data.doi_year
data.yearpost.value_counts()

 0.0    6347
-1.0    6330
-2.0    6294
-3.0    6276
-4.0    6264
 1.0    6130
-5.0    5357
 2.0    5191
-6.0    1152
 3.0     938
-7.0     201
Name: yearpost, dtype: int64

In [22]:
#convert year to datetime
df = data.reset_index()
df['year'] = pd.to_datetime(df['year'], format='%Y')
#add column year to index
df = data.set_index(['year', 'campus'])
#swap indexes
df.index = df.index.swaplevel(0,1)
df[['district', 'doi_year','treatpost',]].tail(5)

                district  doi_year  treatpost
campus    year
253901105 2019    253901    2018.0       True
253901106 2019    253901    2018.0       True
253901107 2019    253901    2018.0       True
254902001 2019    254902    2018.0       True
254902101 2019    254902    2018.0       True

In [24]:
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + students_hisp + students_num + TimeEffects + EntityEffects', df)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0050
Estimator:                   PanelOLS   R-squared (Between):              0.1334
No. Observations:               45962   R-squared (Within):              -0.0245
Date:                Wed, Oct 09 2019   R-squared (Overall):              0.1189
Time:                        18:25:58   Log-likelihood                   -4541.7
Cov. Estimator:             Clustered
                                        F-statistic:                      67.058
Entities:                        6121   P-value                           0.0000
Avg Obs:                       7.5089   Distribution:                 F(3,39831)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             15.556
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(3,39831)
Avg Obs:                       5745.2
Min Obs:                       5598.0
Max Obs:                       5829.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.3110     0.0511     6.0843     0.0000      0.2108      0.4112
treatpost[T.True]    -0.0143     0.0091    -1.5708     0.1162     -0.0321      0.0035
students_hisp        -0.5193     0.0967    -5.3729     0.0000     -0.7088     -0.3299
students_num          0.0002  4.146e-05     4.0690     0.0000   8.745e-05      0.0002
=====================================================================================

F-test for Poolability: 50.910
P-value: 0.0000
Distribution: F(6127,39831)

Included effects: Entity, Time

# Heterogenous effects

In [25]:
### Generate variable for number of hispanic students in year before the district declares

In [26]:
data_pre = data.loc[data.yearpost == -1]
data_pre = data_pre.rename(columns = {'students_hisp': 'students_hisp_pre'})
data_pre['low_avescores_pre'] = np.where(data_pre.avescores < data_pre.avescores.quantile(.25),1, 0)
data_pre['high_avescores_pre'] = np.where(data_pre.avescores > data_pre.avescores.quantile(.75),1,0)
data_pre = data_pre[['campus','students_hisp_pre', 'low_avescores_pre', 'high_avescores_pre']]
data_hte = data.merge(data_pre, on = 'campus', how = 'left')
data_hte['majority_hisp_pre'] = np.where(data_hte.students_hisp_pre > .75, 1, 0)
#df_hte[['students_hisp', 'students_hisp_pre', 'yearpost']].sample(5)

In [27]:
data_pre = data.loc[data.year == 2016]
data_pre['rural_pre'] = np.where(data_pre.type_description == "RURAL", 1, 0)
data_pre['urban_pre'] = np.where(data_pre.type_description == "URBAN", 1, 0)
data_pre = data_pre[['campus','rural_pre', 'urban_pre']]
data_hte = data_hte.merge(data_pre, on = 'campus', how = 'left')
#df_hte[['students_hisp', 'students_hisp_pre', 'yearpost']].sample(5)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

In [28]:
#convert year to datetime
df_hte = data_hte.reset_index()
df_hte['year'] = pd.to_datetime(df_hte['year'], format='%Y')
#add column year to index
df_hte = data_hte.set_index(['year', 'campus'])
#swap indexes
df_hte.index = df_hte.index.swaplevel(0,1)
df_hte[['district', 'doi_year','treatpost',]].tail(20)

                district  doi_year  treatpost
campus    year
251901101 2019    251901    2017.0       True
251901104 2019    251901    2017.0       True
252901001 2019    252901    2017.0       True
252901002 2019    252901    2017.0       True
252901041 2019    252901    2017.0       True
252901101 2019    252901    2017.0       True
252901104 2019    252901    2017.0       True
252901105 2019    252901    2017.0       True
252902002 2019    252902    2017.0       True
252903001 2019    252903    2017.0       True
252903041 2019    252903    2017.0       True
252903101 2019    252903    2017.0       True
253901001 2019    253901    2018.0       True
253901041 2019    253901    2018.0       True
253901101 2019    253901    2018.0       True
253901105 2019    253901    2018.0       True
253901106 2019    253901    2018.0       True
253901107 2019    253901    2018.0       True
254902001 2019    254902    2018.0       True
254902101 2019    254902    2018.0       True

In [31]:
df_hte['treatpost_hisp'] = df_hte.treatpost * df_hte.majority_hisp_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_hisp + students_hisp + students_num + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0107
Estimator:                   PanelOLS   R-squared (Between):              0.1206
No. Observations:               45962   R-squared (Within):              -0.0219
Date:                Wed, Oct 09 2019   R-squared (Overall):              0.1061
Time:                        18:26:53   Log-likelihood                   -4410.1
Cov. Estimator:             Clustered
                                        F-statistic:                      107.78
Entities:                        6121   P-value                           0.0000
Avg Obs:                       7.5089   Distribution:                 F(4,39830)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             31.479
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(4,39830)
Avg Obs:                       5745.2
Min Obs:                       5598.0
Max Obs:                       5829.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.2712     0.0510     5.3181     0.0000      0.1712      0.3711
treatpost[T.True]    -0.0418     0.0095    -4.4111     0.0000     -0.0603     -0.0232
treatpost_hisp        0.1228     0.0144     8.5091     0.0000      0.0946      0.1511
students_hisp        -0.4682     0.0968    -4.8346     0.0000     -0.6580     -0.2784
students_num          0.0002  4.067e-05     4.7876     0.0000      0.0001      0.0003
=====================================================================================

F-test for Poolability: 51.098
P-value: 0.0000
Distribution: F(6127,39830)

Included effects: Entity, Time

In [32]:
df_hte['treatpost_rural'] = df_hte.treatpost * df_hte.rural_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_rural + students_hisp + students_num  + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0051
Estimator:                   PanelOLS   R-squared (Between):              0.1352
No. Observations:               45349   R-squared (Within):              -0.0242
Date:                Wed, Oct 09 2019   R-squared (Overall):              0.1184
Time:                        18:26:56   Log-likelihood                   -4602.8
Cov. Estimator:             Clustered
                                        F-statistic:                      50.926
Entities:                        5870   P-value                           0.0000
Avg Obs:                       7.7256   Distribution:                 F(4,39468)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             12.025
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(4,39468)
Avg Obs:                       5668.6
Min Obs:                       5472.0
Max Obs:                       5784.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.3107     0.0513     6.0585     0.0000      0.2102      0.4113
treatpost[T.True]    -0.0170     0.0093    -1.8312     0.0671     -0.0352      0.0012
treatpost_rural       0.0243     0.0160     1.5194     0.1287     -0.0070      0.0555
students_hisp        -0.5150     0.0968    -5.3193     0.0000     -0.7048     -0.3252
students_num          0.0002  4.172e-05     4.0668     0.0000    8.79e-05      0.0003
=====================================================================================

F-test for Poolability: 51.833
P-value: 0.0000
Distribution: F(5876,39468)

Included effects: Entity, Time

In [33]:
df_hte['treatpost_low'] = df_hte.treatpost * df_hte.low_avescores_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_low + students_hisp + students_num  + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0054
Estimator:                   PanelOLS   R-squared (Between):              0.1295
No. Observations:               44915   R-squared (Within):              -0.0286
Date:                Wed, Oct 09 2019   R-squared (Overall):              0.1122
Time:                        18:27:00   Log-likelihood                   -4575.1
Cov. Estimator:             Clustered
                                        F-statistic:                      52.599
Entities:                        5818   P-value                           0.0000
Avg Obs:                       7.7200   Distribution:                 F(4,39086)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             12.700
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(4,39086)
Avg Obs:                       5614.4
Min Obs:                       5424.0
Max Obs:                       5716.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.3068     0.0515     5.9521     0.0000      0.2058      0.4078
treatpost[T.True]    -0.0252     0.0096    -2.6367     0.0084     -0.0440     -0.0065
treatpost_low         0.0294     0.0129     2.2803     0.0226      0.0041      0.0546
students_hisp        -0.5074     0.0974    -5.2111     0.0000     -0.6982     -0.3165
students_num          0.0002  4.191e-05     4.1315     0.0000   9.101e-05      0.0003
=====================================================================================

F-test for Poolability: 48.663
P-value: 0.0000
Distribution: F(5824,39086)

Included effects: Entity, Time

In [34]:
df_hte['treatpost_high'] = df_hte.treatpost * df_hte.high_avescores_pre
mod = PanelOLS.from_formula('avescores ~ + 1 + treatpost + treatpost_high+ students_hisp + students_num  + TimeEffects + EntityEffects', df_hte)
res = mod.fit(cov_type='clustered', cluster_entity=True)
print(res)

/Users/kylieleblancKylie/anaconda/envs/spacy/lib/python3.7/site-packages/linearmodels/utility.py:478: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  warnings.warn(missing_value_warning_msg, MissingValueWarning)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:              avescores   R-squared:                        0.0050
Estimator:                   PanelOLS   R-squared (Between):              0.1348
No. Observations:               44915   R-squared (Within):              -0.0286
Date:                Wed, Oct 09 2019   R-squared (Overall):              0.1175
Time:                        18:27:03   Log-likelihood                   -4583.2
Cov. Estimator:             Clustered
                                        F-statistic:                      49.075
Entities:                        5818   P-value                           0.0000
Avg Obs:                       7.7200   Distribution:                 F(4,39086)
Min Obs:                       1.0000
Max Obs:                       8.0000   F-statistic (robust):             11.855
                                        P-value                           0.0000
Time periods:                       8   Distribution:                 F(4,39086)
Avg Obs:                       5614.4
Min Obs:                       5424.0
Max Obs:                       5716.0

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
Intercept             0.3130     0.0516     6.0683     0.0000      0.2119      0.4141
treatpost[T.True]    -0.0196     0.0097    -2.0285     0.0425     -0.0386     -0.0007
treatpost_high        0.0078     0.0118     0.6581     0.5105     -0.0154      0.0309
students_hisp        -0.5108     0.0975    -5.2410     0.0000     -0.7018     -0.3198
students_num          0.0002  4.223e-05     3.9316     0.0001   8.325e-05      0.0002
=====================================================================================

F-test for Poolability: 46.534
P-value: 0.0000
Distribution: F(5824,39086)

Included effects: Entity, Time